### ISSUE TITLE
Shutting down source: dynatrace.event_driven_ansible.dt_esa_api error : 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by kubealex** [Dynatrace/Dynatrace-EventDrivenAnsible#17]
**Describe the bug**
In the last few days, I am getting a weird error on the event source startup, it seems that it is having issues retrieving the problems.

**To Reproduce**
1. Import the collection
2. Create a simple rulebook
3. Try to run the rulebook

**Expected behavior**
The rulebook correctly instantiates and the source listens for events

**Additional context**

Simple rulebook to reproduce:

```yaml
- name: Dynatrace | Listen and react to events
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: VALID_URL
        dt_api_token: VALID_TOKEN
        delay: 60
  rules:
    - name: Dynatrace | Sample listener
      condition: event.problemId is defined
      actions:
        - debug:
```

## ERROR
  
```
  2023-09-08 11:11:35,921 - ansible_rulebook.app - INFO - Starting sources
  2023-09-08 11:11:35,921 - ansible_rulebook.app - INFO - Starting rules
  2023-09-08 11:11:35,922 - ansible_rulebook.engine - INFO - run_ruleset
  2023-09-08 11:11:35,924 - drools.ruleset - INFO - Using jar: /home/alerossi/.local/lib/python3.11/site-packages/drools/jars/drools-ansible-rulebook-integration-runtime-1.0.1-SNAPSHOT.jar
  2023-09-08 11:11:37 849 [main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.AbstractRulesEvaluator - Start automatic pseudo clock with a tick every 100 milliseconds
  2023-09-08 11:11:37,855 - ansible_rulebook.engine - INFO - ruleset define: {"name": "Dynatrace | Listen and react to events", "hosts": ["all"], "sources": [{"EventSource": {"name": "dynatrace.event_driven_ansible.dt_esa_api", "source_name": "dynatrace.event_driven_ansible.dt_esa_api", "source_args": {"dt_api_host": "VALID_URL", "dt_api_token": "VALID_TOKEN", "delay": 60}, "source_filters": []}}], "rules": [{"Rule": {"name": "Dynatrace | Sample listener", "condition": {"AllCondition": [{"IsDefinedExpression": {"Event": "problemId"}}]}, "actions": [{"Action": {"action": "debug", "action_args": {}}}], "enabled": true}}]}
  2023-09-08 11:11:37,901 - ansible_rulebook.engine - INFO - load source
  2023-09-08 11:11:39,464 - ansible_rulebook.engine - INFO - load source filters
  2023-09-08 11:11:39,464 - ansible_rulebook.engine - INFO - loading eda.builtin.insert_meta_info
  2023-09-08 11:11:40,955 - ansible_rulebook.engine - INFO - Calling main in dynatrace.event_driven_ansible.dt_esa_api
  test
  2023-09-08 11:11:41,027 - ansible_rulebook.engine - INFO - Waiting for all ruleset tasks to end
  2023-09-08 11:11:41,028 - ansible_rulebook.rule_set_runner - INFO - Waiting for actions on events from Dynatrace | Listen and react to events
  2023-09-08 11:11:41,028 - ansible_rulebook.rule_set_runner - INFO - Waiting for events, ruleset: Dynatrace | Listen and react to events
  2023-09-08 11:11:41 030 [drools-async-evaluator-thread] INFO org.drools.ansible.rulebook.integration.api.io.RuleExecutorChannel - Async channel connected
  2023-09-08 11:11:42,036 - ansible_rulebook.engine - ERROR - Source error
  Traceback (most recent call last):
    File "/home/alerossi/.local/lib/python3.11/site-packages/ansible_rulebook/engine.py", line 172, in start_source
      await entrypoint(fqueue, args)
    File "/home/alerossi/.ansible/collections/ansible_collections/dynatrace/event_driven_ansible/extensions/eda/plugins/event_source/dt_esa_api.py", line 84, in main
      for problem in problems.get("problems"):
  TypeError: 'NoneType' object is not iterable
  2023-09-08 11:11:42,038 - ansible_rulebook.engine - ERROR - Shutting down source: dynatrace.event_driven_ansible.dt_esa_api error : 'NoneType' object is not iterable
  2023-09-08 11:11:42,038 - ansible_rulebook.engine - INFO - Broadcast shutdown to all source plugins
  2023-09-08 11:11:42,039 - ansible_rulebook.engine - INFO - Broadcast to queues: [<Queue at 0x7f90cbca5410 maxsize=1 _getters[1]>]
  2023-09-08 11:11:42,039 - ansible_rulebook.engine - INFO - Broadcasting shutdown: Shutdown(message="Shutting down source: dynatrace.event_driven_ansible.dt_esa_api error : 'NoneType' object is not iterable", delay=60.0, kind='graceful', source_plugin='dynatrace.event_driven_ansible.dt_esa_api')
  2023-09-08 11:11:42,039 - ansible_rulebook.rule_set_runner - INFO - Ruleset: Dynatrace | Listen and react to events, received shutdown: Shutdown(message="Shutting down source: dynatrace.event_driven_ansible.dt_esa_api error : 'NoneType' object is not iterable", delay=60.0, kind='graceful', source_plugin='dynatrace.event_driven_ansible.dt_esa_api')
  2023-09-08 11:11:42,039 - ansible_rulebook.rule_set_runner - INFO - ruleset: Dynatrace | Listen and react to events shutdown no pending work
  2023-09-08 11:11:42,039 - ansible_rulebook.rule_set_runner - INFO - Cleaning up ruleset Dynatrace | Listen and react to events
  2023-09-08 11:11:42 050 [main] INFO org.drools.ansible.rulebook.integration.api.RulesExecutor - Disposing session with id: 1
  2023-09-08 11:11:42,109 - ansible_rulebook.rule_set_runner - INFO - {'asyncResponses': 0,
   'bytesSentOnAsync': 0,
   'end': '2023-09-08T09:11:42.065824215Z',
   'eventsMatched': 0,
   'eventsProcessed': 0,
   'eventsSuppressed': 0,
   'numberOfDisabledRules': 0,
   'numberOfRules': 1,
   'permanentStorageSize': 0,
   'ruleSetName': 'Dynatrace | Listen and react to events',
   'rulesTriggered': 0,
   'sessionId': 1,
   'start': '2023-09-08T09:11:37.833495948Z'}
  2023-09-08 11:11:42,110 - ansible_rulebook.engine - INFO - Cancelling all ruleset tasks
  2023-09-08 11:11:42,110 - ansible_rulebook.engine - INFO - Waiting on gather
  2023-09-08 11:11:42,110 - ansible_rulebook.engine - INFO - Returning from run_rulesets
  2023-09-08 11:11:42,110 - ansible_rulebook.app - INFO - Cancelling event source tasks
  2023-09-08 11:11:42,122 - ansible_rulebook.app - ERROR - 'NoneType' object is not iterable
  2023-09-08 11:11:42,123 - ansible_rulebook.app - INFO - Main complete
  2023-09-08 11:11:42,126 - ansible_rulebook.cli - ERROR - Unexpected exception
  Traceback (most recent call last):
    File "/home/alerossi/.local/lib/python3.11/site-packages/ansible_rulebook/cli.py", line 231, in main
      asyncio.run(app.run(args))
    File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
      return runner.run(main)
             ^^^^^^^^^^^^^^^^
    File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
      return self._loop.run_until_complete(task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
      return future.result()
             ^^^^^^^^^^^^^^^
    File "/home/alerossi/.local/lib/python3.11/site-packages/ansible_rulebook/app.py", line 137, in run
      raise Exception("One of the source plugins failed")
  Exception: One of the source plugins failed
```

## API Call response

```
{
   "totalCount":2,
   "pageSize":10,
   "problems":[
      {
         "problemId":"-5425911857394508157_1692343032144V2",
         "displayId":"P-2308204",
         "title":"Browser monitor local outage",
         "impactLevel":"APPLICATION",
         "severityLevel":"AVAILABILITY",
         "status":"OPEN",
         "affectedEntities":[
            {
               "entityId":{
                  "id":"SYNTHETIC_TEST-67662AE201C4A315",
                  "type":"SYNTHETIC_TEST"
               },
               "name":"EQL - Microservices Demo"
            }
         ],
         "impactedEntities":[
            {
               "entityId":{
                  "id":"SYNTHETIC_TEST-67662AE201C4A315",
                  "type":"SYNTHETIC_TEST"
               },
               "name":"EQL - Microservices Demo"
            }
         ],
         "rootCauseEntity":null,
         "managementZones":[
            
         ],
         "entityTags":[
            {
               "context":"CONTEXTLESS",
               "key":"demo",
               "stringRepresentation":"demo"
            },
            {
               "context":"CONTEXTLESS",
               "key":"client",
               "value":"eql",
               "stringRepresentation":"client:eql"
            }
         ],
         "problemFilters":[
            {
               "id":"408b347f-ec35-30b9-9ed1-a5e631764cd4",
               "name":"EQL-Synth-Failure"
            },
            {
               "id":"6bb63834-1b4e-36b5-b9be-9ae37c64427c",
               "name":"EQL - Microservices Demo"
            },
            {
               "id":"c21f969b-5f03-333d-83e0-4f8f136e7682",
               "name":"Default"
            },
            {
               "id":"81e90a03-4522-37d6-926d-0363a603fb49",
               "name":"SE-GCP-AWS-OCP-Demo-SynthFailure"
            }
         ],
         "startTime":1692343032144,
         "endTime":-1,
         "recentComments":{
            "totalCount":0,
            "comments":[
               
            ]
         }
      },
      {
         "problemId":"5715120975225878994_1692343006503V2",
         "displayId":"P-2308203",
         "title":"Browser monitor local outage",
         "impactLevel":"APPLICATION",
         "severityLevel":"AVAILABILITY",
         "status":"OPEN",
         "affectedEntities":[
            {
               "entityId":{
                  "id":"SYNTHETIC_TEST-60D098EF703EDFB3",
                  "type":"SYNTHETIC_TEST"
               },
               "name":"ESTA - Microservices Demo"
            }
         ],
         "impactedEntities":[
            {
               "entityId":{
                  "id":"SYNTHETIC_TEST-60D098EF703EDFB3",
                  "type":"SYNTHETIC_TEST"
               },
               "name":"ESTA - Microservices Demo"
            }
         ],
         "rootCauseEntity":null,
         "managementZones":[
            
         ],
         "entityTags":[
            {
               "context":"CONTEXTLESS",
               "key":"demo",
               "stringRepresentation":"demo"
            },
            {
               "context":"CONTEXTLESS",
               "key":"client",
               "value":"esta",
               "stringRepresentation":"client:esta"
            }
         ],
         "problemFilters":[
            {
               "id":"65cc52d6-37e8-3856-b783-fd8ba819ed47",
               "name":"ESTA - Microservices Demo"
            },
            {
               "id":"408b347f-ec35-30b9-9ed1-a5e631764cd4",
               "name":"EQL-Synth-Failure"
            },
            {
               "id":"c21f969b-5f03-333d-83e0-4f8f136e7682",
               "name":"Default"
            },
            {
               "id":"XXX",
               "name":"SE-GCP-AWS-OCP-Demo-SynthFailure"
            }
         ],
         "startTime":1692343006503,
         "endTime":-1,
         "recentComments":{
            "totalCount":0,
            "comments":[
               
            ]
         }
      }
   ],
   "warnings":[
      
   ]
}
```

**Comment by mondherGL** [comment]
hello , 

did you resolved the issue ?

regards,

**Comment by kubealex** [comment]
Hi @mondherGL! Yes, somehow I was using the .apps subdomain but the correct one was with .live subdomain.

**Comment by abdulkaderlougue** [comment]
thanks @kubealex that resolved my issue
